### PR TITLE
Integrate cwebbin in texlive

### PR DESCRIPTION
**Pull request by ascherer**
Please ignore.

### CODE REVIEW

**Comment by norbusan** [comment]
;-D

**Comment by ascherer** [comment]
After a successful local `./Build --disable-xdvik`, I submitted the relevant stuff of branch `integrate-cwebbin-in-texlive` to Karl for inspection. As I said before, this PR is large, although it boils down to three genuine patches, a handful of modified files and the contents of tarball `cweb-texlive.tar.gz` created from `CWEBbin` with `debbuild -bi --with texlive SPECS/cwebbin.spec`.

**Comment by ascherer** [comment]
Something like 
```
brew install gettext
brew link gettext --force
```
might be necessary on macos.

I have no idea how to activate `gettext` in `linuxmusl`.

**Comment by norbusan** [comment]
Wait, do you say that gettext library is *required* now, and compilation cannot work without it? That would be rather unfortunate.

**Comment by norbusan** [comment]
Ummpf, indeed, there are already build errors on systems with MUSL installed instead of libc, please check the travis build logs for details:
```
gcc -DHAVE_CONFIG_H -I. -I../../../texk/web2c -I./w2c  -I/texlive/Work/texk -I/texlive/texk  -Wimplicit -Wreturn-type -Wdeclaration-after-statement -Wno-unknown-pragmas -g -O2 -MT ctangleboot.o -MD -MP -MF $depbase.Tpo -c -o ctangleboot.o ctangleboot.c &&\
mv -f $depbase.Tpo $depbase.Po
cwebdir/comm-foo.h:43:22: fatal error: libintl.h: No such file or directory
compilation terminated.
```

**Comment by ascherer** [comment]
Use of `gettext` is one of the major new features of this version of `CWEB`.

As soon as I learn the appropriate `#ifdef`s for darwin and musl, it should be fairly easy to neutralize `gettext` in a few spots (`*-i18n.*` change files).

**Comment by ascherer** [comment]
There seems to be either `gettext-tiny` (flavor `noop`) or `gettext-stub` for `musl` that should do the trick.

**Comment by ascherer** [comment]
`macos` might be dealt with by `#ifdef __APPLE__`.

**Comment by ascherer** [comment]
Solution for macos:
```
#ifdef __APPLE__
#define setlocale(A,B) ""
#define bindtextdomain(A,B) ""
#define textdomain(A) ""
#define gettext(A) A
#else
#include <libintl.h>
#include <locale.h>
#endif
```

If you want to use `GNU gettext utilities`, install with
```
brew install gettext
brew link --force gettext
```

**Comment by ascherer** [comment]
A more generic approach can be found in `libs/icu`. It wraps the `gettext` stuff with
```
#ifndef HAVE_GETTEXT
#define HAVE_GETTEXT 0
#endif

#if HAVE_GETTEXT
#include <libintl.h>
#include <locale.h>
...
#else 
/* see above for __APPLE__ */
...
#endif
```
I think I'll use this in another commit.

**Comment by norbusan** [comment]
> I think I'll use this in another commit.

That would be a good idea!

**Comment by ascherer** [comment]
I've squashed all commits related to the `CWEBbin` interface to make clear that there are _two_ remaining commits with changes to code outside `cwebdir/` that be applied before and after the new interface tarball gets extracted.

**Pull request closed without merging**
